version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./notesapp-server
    ports:
      - "5000:5000"
    environment:
      - .env

  ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./notesapp-ui
    ports:
      - "3000:3000"

